[package]
name = "imagetext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
emoji = ["once_cell", "emojis", "regex", "include_dir", "fxhash"]

[dependencies]
tiny-skia = "0.8.2"
rusttype = "0.9.3"
image = "0.24.5"

once_cell = { version = "1.17.0", optional = true }
emojis = { version = "0.5.2", optional = true }
regex = { version = "1.7.1", optional = true }
include_dir = { version = "0.7.3", optional = true }
fxhash = { version = "0.2.1", optional = true }

[dev-dependencies]
imagetext = { path = ".", features = ["emoji"] }